#!/usr/bin/python
Import('env')

xrlist_test_sources  = Split("""list.c""")

test_xrlist = env.Program('test_xrlist',
  xrlist_test_sources,
  LIBS=['xrlist'],
  CFLAGS='-g -Werror -Wall -I.',
  LIBPATH=['..','/usr/lib'])


xrl_alias = Alias('test', [test_xrlist], test_xrlist[0].path)


AlwaysBuild(xrl_alias)
